# fly.toml app configuration file generated for api-red-sound-7022 on 2025-03-22T01:52:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-red-sound-7022'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
